### ISSUE TITLE
how work

### ISSUE THREAD

**Issue by yebuq** [hermesdj/VRisingServerApiPlugin#1]
how do this work，copy to root path？

**Comment by hermesdj** [comment]
It is still in active development so not ready to be used yet, but you can test it by building the DLL and moving it to the BepInEx folder of your VRising server (BepInEx/plugins directory). I'll fill the README when its ready

**Comment by yebuq** [comment]
> It is still in active development so not ready to be used yet, but you can test it by building the DLL and moving it to the BepInEx folder of your VRising server (BepInEx/plugins directory). I'll fill the README when its ready

 hope provide  DLL download , thx for that

**Comment by hermesdj** [comment]
Yes I have a few stuff to finish first and I will configure a mechanism to create a release and publish the dll compiled =)
